(() => {
  'use strict';
  const catalogs = {
    es: {
      'La Cuenta · Comptador de taula': 'La Cuenta · Contador de mesa', 'La Cuenta · Controlador de torneig': 'La Cuenta · Controlador de torneo',
      'Inici del comptador': 'Inicio del contador', 'Inici del torneig': 'Inicio del torneo', 'Comptador no oficial': 'Contador no oficial', 'Control de torneig': 'Control de torneo',
      'Taula': 'Mesa', 'Torneig': 'Torneo', 'Instal·la': 'Instalar', 'Partida nova': 'Nueva partida', 'Qui acabarà pagant?': '¿Quién acabará pagando?',
      'Identifica els participants, registra cada compte i controla automàticament els estalvis.': 'Identifica a los participantes, registra cada cuenta y controla automáticamente los ahorros.',
      'participants': 'participantes', 'Participants': 'Participantes', 'Entre 3 i 8. El límit inicial s’ajusta automàticament segons les regles.': 'Entre 3 y 8. El límite inicial se ajusta automáticamente según las reglas.',
      'Estalvis inicials per persona': 'Ahorros iniciales por persona', 'Nom o número de taula (opcional)': 'Nombre o número de mesa (opcional)', 'Taula 1': 'Mesa 1', '+ Afegir participant': '+ Añadir participante', 'Començar partida': 'Empezar partida',
      'Hi ha una partida en curs': 'Hay una partida en curso', 'Continua-la →': 'Continuarla →', 'Partida en curs': 'Partida en curso', 'Ronda': 'Ronda', 'Desfés': 'Deshacer', 'Finalitza': 'Finalizar',
      'Registra el cobrament': 'Registra el cobro', 'El pagament que deixa algú a 0 € tanca la partida.': 'El pago que deja a alguien en 0 € termina la partida.', 'Import del compte': 'Importe de la cuenta',
      'Qui demana el compte?': '¿Quién pide la cuenta?', 'Forma de pagament': 'Forma de pago', 'Una persona': 'Una persona', 'Paga el compte sencer': 'Paga toda la cuenta', 'A mitges': 'A medias', 'Carta ×3 · 50% cadascú': 'Carta ×3 · 50% cada uno',
      'A patxes': 'A escote', 'Carta ×1 · entre els presents': 'Carta ×1 · entre los presentes', 'Manual': 'Manual', 'Qualsevol repartiment': 'Cualquier reparto', 'Amb qui paga a mitges?': '¿Con quién paga a medias?',
      'Qui participa en el pagament?': '¿Quién participa en el pago?', 'Desmarca qui sigui al lavabo o celebri l’aniversari.': 'Desmarca a quien esté en el baño o celebre su cumpleaños.', 'Import carregat a cada participant': 'Importe cargado a cada participante',
      'Propina': 'Propina', 'Carta ×6 · suma la tapa més barata': 'Carta ×6 · suma la tapa más barata', 'Tapa més barata': 'Tapa más barata', 'Total final': 'Total final', 'Introdueix un import per veure el repartiment.': 'Introduce un importe para ver el reparto.',
      'El sol·licitant augmenta la seva mà en +1': 'Quien pide la cuenta aumenta su mano en +1', 'Registrar ronda': 'Registrar ronda', 'Recordatori de cartes especials': 'Recordatorio de cartas especiales',
      'Plat cremat ×8': 'Plato quemado ×8', 'Bloqueja un tipus de tapa.': 'Bloquea un tipo de tapa.', 'Canvi de sentit ×4': 'Cambio de sentido ×4', 'Inverteix l’ordre de torn.': 'Invierte el orden de turno.', 'Premium ×4': 'Premium ×4', 'Dobla el valor del plat jugat.': 'Duplica el valor del plato jugado.',
      'Toilette ×5': 'Baño ×5', 'No pots ser escollit ni pagar.': 'No puedes ser elegido ni pagar.', 'Cafè ×10': 'Café ×10', 'Tanca les comandes habituals.': 'Cierra los pedidos habituales.', 'Aniversari ×1': 'Cumpleaños ×1', 'No estàs obligat a jugar ni pagar.': 'No estás obligado a jugar ni pagar.',
      'El compte es divideix entre dues persones.': 'La cuenta se divide entre dos personas.', 'Es divideix entre tots els presents.': 'Se divide entre todos los presentes.', 'S’hi suma la tapa més barata.': 'Se añade la tapa más barata.', 'Historial': 'Historial', 'Rondes registrades': 'Rondas registradas', 'Encara no s’ha registrat cap ronda.': 'Todavía no se ha registrado ninguna ronda.',
      'Resultat final': 'Resultado final', 'Partida acabada': 'Partida terminada', 'Comparteix amb el torneig': 'Compartir con el torneo', 'Escaneja aquest QR des del controlador. Inclou només la taula, els noms i els resultats finals.': 'Escanea este QR desde el controlador. Incluye solo la mesa, los nombres y los resultados finales.',
      'Comparteix l’enllaç': 'Compartir el enlace', 'Torna a la partida': 'Volver a la partida', 'Múltiples taules · múltiples partides': 'Múltiples mesas · múltiples partidas', 'Escaneja els resultats finals, confirma les coincidències de noms i construeix la classificació general.': 'Escanea los resultados finales, confirma las coincidencias de nombres y crea la clasificación general.',
      'Escaneja un QR': 'Escanear un QR', 'Llegeix una imatge': 'Leer una imagen', 'Partides': 'Partidas', 'Taules': 'Mesas', 'Classificació': 'Clasificación', 'Resultat acumulat': 'Resultado acumulado', 'Ordenat per victòries, percentatge mitjà conservat i estalvis totals.': 'Ordenado por victorias, porcentaje medio conservado y ahorros totales.',
      'Registre': 'Registro', 'Partides incorporades': 'Partidas incorporadas', 'Exporta còpia': 'Exportar copia', 'Importa còpia': 'Importar copia', 'Encara no hi ha cap resultat. Escaneja el QR d’una taula.': 'Todavía no hay resultados. Escanea el QR de una mesa.', 'Identitats': 'Identidades', 'Participants reconeguts': 'Participantes reconocidos',
      'Pots corregir un nom o fusionar duplicats després d’una importació.': 'Puedes corregir un nombre o fusionar duplicados después de una importación.', 'No hi ha participants.': 'No hay participantes.', 'Fusiona dos participants': 'Fusionar dos participantes', 'absorbeix': 'absorbe a', 'Fusiona': 'Fusionar', 'Esborra tot el torneig d’aquest dispositiu': 'Borrar todo el torneo de este dispositivo',
      'Càmera': 'Cámara', 'Enquadra el QR': 'Encuadra el QR', 'Preparant la càmera…': 'Preparando la cámara…', 'Revisa abans d’incorporar': 'Revisa antes de incorporar', 'Resultat escanejat': 'Resultado escaneado', 'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències exactes s’han preseleccionat.': 'Para cada nombre, confirma si es una persona existente o una incorporación nueva. Las coincidencias exactas están preseleccionadas.', 'Incorpora el resultat': 'Incorporar el resultado',
      'Eina gratuïta, no oficial i sense afiliació amb 2Tomatoes Games.': 'Herramienta gratuita, no oficial y sin afiliación con 2Tomatoes Games.', 'La Cuenta © 2Tomatoes Games · Joc de Litus Carreras · Art original d’Ariadna Altimira. Aquesta web no reutilitza recursos gràfics del joc.': 'La Cuenta © 2Tomatoes Games · Juego de Litus Carreras · Arte original de Ariadna Altimira. Esta web no reutiliza recursos gráficos del juego.',
      'Nom': 'Nombre', 'Elimina aquest participant': 'Eliminar este participante', 'Tanca': 'Cerrar', 'Cancel·la': 'Cancelar', 'Elimina aquest resultat': 'Eliminar este resultado', 'Nom del participant': 'Nombre del participante', 'Participant que es conserva': 'Participante que se conserva', 'Participant duplicat': 'Participante duplicado'
    },
    eu: {
      'La Cuenta · Comptador de taula': 'La Cuenta · Mahaiko kontagailua', 'La Cuenta · Controlador de torneig': 'La Cuenta · Txapelketa-kontrola', 'Inici del comptador': 'Kontagailuaren hasiera', 'Inici del torneig': 'Txapelketaren hasiera', 'Comptador no oficial': 'Kontagailu ez-ofiziala', 'Control de torneig': 'Txapelketa-kontrola',
      'Taula': 'Mahaia', 'Torneig': 'Txapelketa', 'Instal·la': 'Instalatu', 'Partida nova': 'Partida berria', 'Qui acabarà pagant?': 'Nork ordainduko du azkenean?', 'Identifica els participants, registra cada compte i controla automàticament els estalvis.': 'Identifikatu parte-hartzaileak, erregistratu kontu bakoitza eta kontrolatu aurrezkiak automatikoki.',
      'participants': 'parte-hartzaile', 'Participants': 'Parte-hartzaileak', 'Entre 3 i 8. El límit inicial s’ajusta automàticament segons les regles.': '3 eta 8 artean. Hasierako muga automatikoki egokitzen da arauen arabera.', 'Estalvis inicials per persona': 'Pertsona bakoitzaren hasierako aurrezkiak', 'Nom o número de taula (opcional)': 'Mahaiaren izena edo zenbakia (aukerakoa)', 'Taula 1': '1. mahaia', '+ Afegir participant': '+ Gehitu parte-hartzailea', 'Començar partida': 'Hasi partida',
      'Hi ha una partida en curs': 'Partida bat abian dago', 'Continua-la →': 'Jarraitu →', 'Partida en curs': 'Partida abian', 'Ronda': 'Txanda', 'Desfés': 'Desegin', 'Finalitza': 'Amaitu', 'Registra el cobrament': 'Erregistratu ordainketa', 'El pagament que deixa algú a 0 € tanca la partida.': 'Norbait 0 €-tan uzten duen ordainketak partida amaitzen du.', 'Import del compte': 'Kontuaren zenbatekoa', 'Qui demana el compte?': 'Nork eskatzen du kontua?',
      'Forma de pagament': 'Ordainketa modua', 'Una persona': 'Pertsona bat', 'Paga el compte sencer': 'Kontu osoa ordaintzen du', 'A mitges': 'Erdibana', 'Carta ×3 · 50% cadascú': 'Karta ×3 · %50 bakoitzak', 'A patxes': 'Denon artean', 'Carta ×1 · entre els presents': 'Karta ×1 · bertaratutakoen artean', 'Manual': 'Eskuz', 'Qualsevol repartiment': 'Edozein banaketa', 'Amb qui paga a mitges?': 'Norekin ordaintzen du erdibana?',
      'Qui participa en el pagament?': 'Nork parte hartzen du ordainketan?', 'Desmarca qui sigui al lavabo o celebri l’aniversari.': 'Desmarkatu komunean dagoena edo urtebetetzea ospatzen duena.', 'Import carregat a cada participant': 'Parte-hartzaile bakoitzari kobratutako zenbatekoa', 'Propina': 'Eskupekoa', 'Carta ×6 · suma la tapa més barata': 'Karta ×6 · gehitu tapa merkeena', 'Tapa més barata': 'Tapa merkeena', 'Total final': 'Azken guztizkoa', 'Introdueix un import per veure el repartiment.': 'Sartu zenbateko bat banaketa ikusteko.',
      'El sol·licitant augmenta la seva mà en +1': 'Kontua eskatzen duenak eskua +1 handitzen du', 'Registrar ronda': 'Erregistratu txanda', 'Recordatori de cartes especials': 'Karta berezien oroigarria', 'Plat cremat ×8': 'Plater errea ×8', 'Bloqueja un tipus de tapa.': 'Tapa mota bat blokeatzen du.', 'Canvi de sentit ×4': 'Noranzko-aldaketa ×4', 'Inverteix l’ordre de torn.': 'Txanden ordena alderantzikatzen du.', 'Premium ×4': 'Premium ×4', 'Dobla el valor del plat jugat.': 'Jokatutako plateraren balioa bikoizten du.',
      'Toilette ×5': 'Komuna ×5', 'No pots ser escollit ni pagar.': 'Ezin zaituzte aukeratu eta ezin duzu ordaindu.', 'Cafè ×10': 'Kafea ×10', 'Tanca les comandes habituals.': 'Ohiko eskaerak ixten ditu.', 'Aniversari ×1': 'Urtebetetzea ×1', 'No estàs obligat a jugar ni pagar.': 'Ez zaude jokatzera edo ordaintzera behartuta.', 'El compte es divideix entre dues persones.': 'Kontua bi pertsonaren artean banatzen da.', 'Es divideix entre tots els presents.': 'Bertaratutako guztien artean banatzen da.', 'S’hi suma la tapa més barata.': 'Tapa merkeena gehitzen da.',
      'Historial': 'Historia', 'Rondes registrades': 'Erregistratutako txandak', 'Encara no s’ha registrat cap ronda.': 'Oraindik ez da txandarik erregistratu.', 'Resultat final': 'Azken emaitza', 'Partida acabada': 'Partida amaituta', 'Comparteix amb el torneig': 'Partekatu txapelketarekin', 'Escaneja aquest QR des del controlador. Inclou només la taula, els noms i els resultats finals.': 'Eskaneatu QR hau kontroletik. Mahaia, izenak eta azken emaitzak bakarrik ditu.', 'Comparteix l’enllaç': 'Partekatu esteka', 'Torna a la partida': 'Itzuli partidara',
      'Múltiples taules · múltiples partides': 'Mahai anitz · partida anitz', 'Escaneja els resultats finals, confirma les coincidències de noms i construeix la classificació general.': 'Eskaneatu azken emaitzak, baieztatu izen-kointzidentziak eta osatu sailkapen orokorra.', 'Escaneja un QR': 'Eskaneatu QR bat', 'Llegeix una imatge': 'Irakurri irudi bat', 'Partides': 'Partidak', 'Taules': 'Mahaiak', 'Classificació': 'Sailkapena', 'Resultat acumulat': 'Emaitza metatua', 'Ordenat per victòries, percentatge mitjà conservat i estalvis totals.': 'Garaipenen, mantendutako batez besteko ehunekoaren eta guztizko aurrezkien arabera ordenatua.',
      'Registre': 'Erregistroa', 'Partides incorporades': 'Gehitutako partidak', 'Exporta còpia': 'Esportatu kopia', 'Importa còpia': 'Inportatu kopia', 'Encara no hi ha cap resultat. Escaneja el QR d’una taula.': 'Oraindik ez dago emaitzarik. Eskaneatu mahai bateko QR-a.', 'Identitats': 'Identitateak', 'Participants reconeguts': 'Ezagututako parte-hartzaileak', 'Pots corregir un nom o fusionar duplicats després d’una importació.': 'Izen bat zuzendu edo bikoiztuak batu ditzakezu inportatu ondoren.', 'No hi ha participants.': 'Ez dago parte-hartzailerik.', 'Fusiona dos participants': 'Batu bi parte-hartzaile', 'absorbeix': 'barneratzen du', 'Fusiona': 'Batu', 'Esborra tot el torneig d’aquest dispositiu': 'Ezabatu txapelketa osoa gailu honetatik',
      'Càmera': 'Kamera', 'Enquadra el QR': 'Kokatu QR-a markoan', 'Preparant la càmera…': 'Kamera prestatzen…', 'Revisa abans d’incorporar': 'Berrikusi gehitu aurretik', 'Resultat escanejat': 'Eskaneatutako emaitza', 'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències exactes s’han preseleccionat.': 'Izen bakoitzean, baieztatu lehendik dagoen pertsona den ala berria. Bat-etortze zehatzak aurrez hautatu dira.', 'Incorpora el resultat': 'Gehitu emaitza',
      'Eina gratuïta, no oficial i sense afiliació amb 2Tomatoes Games.': 'Doako tresna ez-ofiziala, 2Tomatoes Games-ekin loturarik gabea.', 'La Cuenta © 2Tomatoes Games · Joc de Litus Carreras · Art original d’Ariadna Altimira. Aquesta web no reutilitza recursos gràfics del joc.': 'La Cuenta © 2Tomatoes Games · Litus Carrerasen jokoa · Ariadna Altimiraren jatorrizko artea. Webgune honek ez ditu jokoaren baliabide grafikoak berrerabiltzen.',
      'Nom': 'Izena', 'Elimina aquest participant': 'Ezabatu parte-hartzaile hau', 'Tanca': 'Itxi', 'Cancel·la': 'Utzi', 'Elimina aquest resultat': 'Ezabatu emaitza hau', 'Nom del participant': 'Parte-hartzailearen izena', 'Participant que es conserva': 'Mantenduko den parte-hartzailea', 'Participant duplicat': 'Parte-hartzaile bikoiztua'
    },
    gl: {
      'La Cuenta · Comptador de taula': 'La Cuenta · Contador de mesa', 'La Cuenta · Controlador de torneig': 'La Cuenta · Controlador de torneo', 'Inici del comptador': 'Inicio do contador', 'Inici del torneig': 'Inicio do torneo', 'Comptador no oficial': 'Contador non oficial', 'Control de torneig': 'Control de torneo',
      'Taula': 'Mesa', 'Torneig': 'Torneo', 'Instal·la': 'Instalar', 'Partida nova': 'Nova partida', 'Qui acabarà pagant?': 'Quen acabará pagando?', 'Identifica els participants, registra cada compte i controla automàticament els estalvis.': 'Identifica as persoas participantes, rexistra cada conta e controla automaticamente os aforros.', 'participants': 'participantes', 'Participants': 'Participantes', 'Entre 3 i 8. El límit inicial s’ajusta automàticament segons les regles.': 'Entre 3 e 8. O límite inicial axústase automaticamente segundo as regras.', 'Estalvis inicials per persona': 'Aforros iniciais por persoa', 'Nom o número de taula (opcional)': 'Nome ou número da mesa (opcional)', 'Taula 1': 'Mesa 1', '+ Afegir participant': '+ Engadir participante', 'Començar partida': 'Comezar partida',
      'Hi ha una partida en curs': 'Hai unha partida en curso', 'Continua-la →': 'Continuar →', 'Partida en curs': 'Partida en curso', 'Ronda': 'Rolda', 'Desfés': 'Desfacer', 'Finalitza': 'Finalizar', 'Registra el cobrament': 'Rexistra o cobro', 'El pagament que deixa algú a 0 € tanca la partida.': 'O pagamento que deixa alguén en 0 € remata a partida.', 'Import del compte': 'Importe da conta', 'Qui demana el compte?': 'Quen pide a conta?', 'Forma de pagament': 'Forma de pagamento', 'Una persona': 'Unha persoa', 'Paga el compte sencer': 'Paga a conta enteira', 'A mitges': 'A medias', 'Carta ×3 · 50% cadascú': 'Carta ×3 · 50% cada persoa', 'A patxes': 'A partes', 'Carta ×1 · entre els presents': 'Carta ×1 · entre as persoas presentes', 'Manual': 'Manual', 'Qualsevol repartiment': 'Calquera reparto', 'Amb qui paga a mitges?': 'Con quen paga a medias?',
      'Qui participa en el pagament?': 'Quen participa no pagamento?', 'Desmarca qui sigui al lavabo o celebri l’aniversari.': 'Desmarca quen estea no baño ou celebre o aniversario.', 'Import carregat a cada participant': 'Importe cargado a cada participante', 'Propina': 'Propina', 'Carta ×6 · suma la tapa més barata': 'Carta ×6 · suma a tapa máis barata', 'Tapa més barata': 'Tapa máis barata', 'Total final': 'Total final', 'Introdueix un import per veure el repartiment.': 'Introduce un importe para ver o reparto.', 'El sol·licitant augmenta la seva mà en +1': 'Quen pide a conta aumenta a súa man en +1', 'Registrar ronda': 'Rexistrar rolda', 'Recordatori de cartes especials': 'Recordatorio de cartas especiais',
      'Plat cremat ×8': 'Prato queimado ×8', 'Bloqueja un tipus de tapa.': 'Bloquea un tipo de tapa.', 'Canvi de sentit ×4': 'Cambio de sentido ×4', 'Inverteix l’ordre de torn.': 'Inverte a orde da quenda.', 'Premium ×4': 'Premium ×4', 'Dobla el valor del plat jugat.': 'Duplica o valor do prato xogado.', 'Toilette ×5': 'Baño ×5', 'No pots ser escollit ni pagar.': 'Non podes ser elixido nin pagar.', 'Cafè ×10': 'Café ×10', 'Tanca les comandes habituals.': 'Pecha os pedidos habituais.', 'Aniversari ×1': 'Aniversario ×1', 'No estàs obligat a jugar ni pagar.': 'Non estás obrigado a xogar nin pagar.', 'El compte es divideix entre dues persones.': 'A conta divídese entre dúas persoas.', 'Es divideix entre tots els presents.': 'Divídese entre todas as persoas presentes.', 'S’hi suma la tapa més barata.': 'Engádese a tapa máis barata.',
      'Historial': 'Historial', 'Rondes registrades': 'Roldas rexistradas', 'Encara no s’ha registrat cap ronda.': 'Aínda non se rexistrou ningunha rolda.', 'Resultat final': 'Resultado final', 'Partida acabada': 'Partida rematada', 'Comparteix amb el torneig': 'Compartir co torneo', 'Escaneja aquest QR des del controlador. Inclou només la taula, els noms i els resultats finals.': 'Escanea este QR desde o controlador. Inclúe só a mesa, os nomes e os resultados finais.', 'Comparteix l’enllaç': 'Compartir a ligazón', 'Torna a la partida': 'Volver á partida',
      'Múltiples taules · múltiples partides': 'Múltiples mesas · múltiples partidas', 'Escaneja els resultats finals, confirma les coincidències de noms i construeix la classificació general.': 'Escanea os resultados finais, confirma as coincidencias de nomes e constrúe a clasificación xeral.', 'Escaneja un QR': 'Escanear un QR', 'Llegeix una imatge': 'Ler unha imaxe', 'Partides': 'Partidas', 'Taules': 'Mesas', 'Classificació': 'Clasificación', 'Resultat acumulat': 'Resultado acumulado', 'Ordenat per victòries, percentatge mitjà conservat i estalvis totals.': 'Ordenado por vitorias, porcentaxe media conservada e aforros totais.', 'Registre': 'Rexistro', 'Partides incorporades': 'Partidas incorporadas', 'Exporta còpia': 'Exportar copia', 'Importa còpia': 'Importar copia', 'Encara no hi ha cap resultat. Escaneja el QR d’una taula.': 'Aínda non hai resultados. Escanea o QR dunha mesa.',
      'Identitats': 'Identidades', 'Participants reconeguts': 'Participantes recoñecidos', 'Pots corregir un nom o fusionar duplicats després d’una importació.': 'Podes corrixir un nome ou fusionar duplicados despois dunha importación.', 'No hi ha participants.': 'Non hai participantes.', 'Fusiona dos participants': 'Fusionar dous participantes', 'absorbeix': 'absorbe a', 'Fusiona': 'Fusionar', 'Esborra tot el torneig d’aquest dispositiu': 'Borrar todo o torneo deste dispositivo', 'Càmera': 'Cámara', 'Enquadra el QR': 'Enmarca o QR', 'Preparant la càmera…': 'Preparando a cámara…', 'Revisa abans d’incorporar': 'Revisa antes de incorporar', 'Resultat escanejat': 'Resultado escaneado', 'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències exactes s’han preseleccionat.': 'Para cada nome, confirma se é unha persoa existente ou unha incorporación nova. As coincidencias exactas están preseleccionadas.', 'Incorpora el resultat': 'Incorporar o resultado',
      'Eina gratuïta, no oficial i sense afiliació amb 2Tomatoes Games.': 'Ferramenta gratuíta, non oficial e sen afiliación con 2Tomatoes Games.', 'La Cuenta © 2Tomatoes Games · Joc de Litus Carreras · Art original d’Ariadna Altimira. Aquesta web no reutilitza recursos gràfics del joc.': 'La Cuenta © 2Tomatoes Games · Xogo de Litus Carreras · Arte orixinal de Ariadna Altimira. Esta web non reutiliza recursos gráficos do xogo.',
      'Nom': 'Nome', 'Elimina aquest participant': 'Eliminar este participante', 'Tanca': 'Pechar', 'Cancel·la': 'Cancelar', 'Elimina aquest resultat': 'Eliminar este resultado', 'Nom del participant': 'Nome do participante', 'Participant que es conserva': 'Participante que se conserva', 'Participant duplicat': 'Participante duplicado'
    }
  };
  const extras = {
    es: {
      'Idioma': 'Idioma', 'Participant': 'Participante', 'Mà': 'Mano', 'de': 'de', 'Compte': 'Cuenta', 'propina': 'propina', 'rondes': 'rondas', 'partides': 'partidas', 'també': 'también', 'finalitzada': 'finalizada', 'posició': 'posición', 'Configuració del torneig': 'Configuración del torneo', 'Nom del torneig': 'Nombre del torneo', 'Torneig de La Cuenta': 'Torneo de La Cuenta', 'Rondes de torneig': 'Rondas de torneo', 'Pitjors resultats descartats': 'Peores resultados descartados', 'Compten els 3 millors resultats de cada participant.': 'Cuentan los 3 mejores resultados de cada participante.', 'Ronda del torneig': 'Ronda del torneo',
      'Desempat oficial': 'Desempate oficial', 'Si hi ha empat en estalvis, guanya qui porti més diners a sobre. Introdueix-los només per a les persones empatades.': 'Si hay empate en ahorros, gana quien lleve más dinero encima. Introdúcelo solo para las personas empatadas.', 'Aplica el desempat': 'Aplicar el desempate',
      'Guanya qui acumula més diners finals. Els empats mantenen la mateixa posició.': 'Gana quien acumula más dinero final. Los empates mantienen la misma posición.',
      'Escriu el nom de tots els participants.': 'Escribe el nombre de todos los participantes.', 'Els noms han de ser diferents dins de la mateixa taula.': 'Los nombres deben ser distintos dentro de la misma mesa.', 'La partida en curs se substituirà. Vols continuar?': 'Se sustituirá la partida en curso. ¿Quieres continuar?', 'Taula sense número': 'Mesa sin número',
      'Selecciona com es reparteix el compte.': 'Selecciona cómo se reparte la cuenta.', 'A patxes necessita almenys una persona seleccionada.': 'A escote necesita al menos una persona seleccionada.', 'El repartiment manual suma {allocated} i ha de sumar {total}.': 'El reparto manual suma {allocated} y debe sumar {total}.', '{players} arribarà o superarà el topall i la partida haurà acabat.': '{players} llegará o superará el límite y la partida habrá terminado.', '{player} ja té el màxim de 10 cartes a la mà.': '{player} ya tiene el máximo de 10 cartas en la mano.',
      'Revisa el repartiment abans de registrar la ronda.': 'Revisa el reparto antes de registrar la ronda.', 'Ronda registrada.': 'Ronda registrada.', 'S’ha desfet l’última ronda.': 'Se ha deshecho la última ronda.', 'Registra almenys una ronda abans de finalitzar.': 'Registra al menos una ronda antes de finalizar.', 'Algú ha arribat o superat el topall. La partida ha acabat.': 'Alguien ha alcanzado o superado el límite. La partida ha terminado.', 'Ha pagat': 'Ha pagado', 'porta': 'lleva', 'Resultat': 'Resultado', 'Resultat final de la partida': 'Resultado final de la partida', 'Enllaç copiat.': 'Enlace copiado.', 'No s’ha pogut compartir. Mantén premut el QR per mostrar-lo.': 'No se ha podido compartir. Mantén pulsado el QR para mostrarlo.', 'Desempat aplicat.': 'Desempate aplicado.',
      'Aquest QR no és un resultat compatible.': 'Este QR no es un resultado compatible.', 'El resultat ha de contenir entre 3 i 8 participants.': 'El resultado debe contener entre 3 y 8 participantes.', 'El resultat conté dades incompletes.': 'El resultado contiene datos incompletos.', 'No s’ha pogut carregar el generador QR.': 'No se ha podido cargar el generador QR.', 'A iOS: Compartir → Afegeix a la pantalla d’inici.': 'En iOS: Compartir → Añadir a la pantalla de inicio.', 'Obre el menú del navegador i tria “Instal·la l’aplicació”.': 'Abre el menú del navegador y elige «Instalar aplicación».',
      'La classificació apareixerà després d’incorporar el primer QR.': 'La clasificación aparecerá después de incorporar el primer QR.', 'Pos.': 'Pos.', 'Victòries': 'Victorias', 'Conservat': 'Conservado', 'Estalvis totals': 'Ahorros totales', 'Compten': 'Cuentan', 'Descarts': 'Descartes', 'Diners computables': 'Dinero computable', 'Ronda de torneig': 'Ronda de torneo', 'rondes internes': 'rondas internas', 'descartat': 'descartado', 'Compten els {counted} millors resultats de cada participant.': 'Cuentan los {counted} mejores resultados de cada participante.', '{players} ja té resultat a la ronda {round}.': '{players} ya tiene resultado en la ronda {round}.', 'Participant eliminat': 'Participante eliminado', 'Aquest navegador no permet accedir a la càmera. Prova “Llegeix una imatge”.': 'Este navegador no permite acceder a la cámara. Prueba «Leer una imagen».', 'Dona permís a la càmera i enquadra el QR.': 'Da permiso a la cámara y encuadra el QR.', 'Buscant el codi…': 'Buscando el código…', 'No s’ha pogut obrir la càmera. Revisa el permís o llegeix una imatge.': 'No se ha podido abrir la cámara. Revisa el permiso o lee una imagen.', 'No s’ha trobat cap QR llegible a la imatge.': 'No se ha encontrado ningún QR legible en la imagen.', 'No s’ha pogut llegir la imatge.': 'No se ha podido leer la imagen.', 'Aquesta partida ja havia estat incorporada.': 'Esta partida ya se había incorporado.', 'QR no reconegut.': 'QR no reconocido.',
      'Identitat al torneig': 'Identidad en el torneo', 'Persona nova': 'Persona nueva', 'Coincidència': 'Coincidencia', 'Potser': 'Posible', 'Dos noms de la mateixa taula no poden correspondre a una sola persona.': 'Dos nombres de la misma mesa no pueden corresponder a una sola persona.', 'Resultat incorporat al torneig.': 'Resultado incorporado al torneo.', 'Vols eliminar aquest resultat del torneig?': '¿Quieres eliminar este resultado del torneo?', 'Resultat eliminat.': 'Resultado eliminado.', 'Aquest nom ja correspon a un altre participant. Pots fusionar-los.': 'Este nombre ya corresponde a otro participante. Puedes fusionarlos.', 'Nom actualitzat.': 'Nombre actualizado.', 'Selecciona dues persones diferents.': 'Selecciona dos personas distintas.', 'Vols fusionar “{remove}” dins de “{keep}”?': '¿Quieres fusionar «{remove}» dentro de «{keep}»?', 'Participants fusionats.': 'Participantes fusionados.', 'La còpia substituirà el torneig actual. Vols continuar?': 'La copia sustituirá el torneo actual. ¿Quieres continuar?', 'Còpia restaurada.': 'Copia restaurada.', 'El fitxer no és una còpia vàlida del torneig.': 'El archivo no es una copia válida del torneo.', 'Vols esborrar totes les partides i participants d’aquest torneig?': '¿Quieres borrar todas las partidas y participantes de este torneo?', 'Torneig esborrat.': 'Torneo borrado.'
    },
    eu: {
      'Idioma': 'Hizkuntza', 'Participant': 'Parte-hartzailea', 'Mà': 'Eskua', 'de': '/', 'Compte': 'Kontua', 'propina': 'eskupekoa', 'rondes': 'txanda', 'partides': 'partida', 'també': 'baita', 'finalitzada': 'amaituta', 'posició': 'postua', 'Configuració del torneig': 'Txapelketaren konfigurazioa', 'Nom del torneig': 'Txapelketaren izena', 'Torneig de La Cuenta': 'La Cuenta txapelketa', 'Rondes de torneig': 'Txapelketa-txandak', 'Pitjors resultats descartats': 'Baztertutako emaitza txarrenak', 'Compten els 3 millors resultats de cada participant.': 'Parte-hartzaile bakoitzaren 3 emaitza onenak zenbatzen dira.', 'Ronda del torneig': 'Txapelketako txanda',
      'Desempat oficial': 'Desberdinketa ofiziala', 'Si hi ha empat en estalvis, guanya qui porti més diners a sobre. Introdueix-los només per a les persones empatades.': 'Aurrezkietan berdinketa badago, gainean diru gehien daramanak irabazten du. Sartu zenbatekoa berdindutako pertsonentzat bakarrik.', 'Aplica el desempat': 'Aplikatu desberdinketa', 'Guanya qui acumula més diners finals. Els empats mantenen la mateixa posició.': 'Azken diru gehien metatzen duenak irabazten du. Berdinketek postu bera mantentzen dute.',
      'Escriu el nom de tots els participants.': 'Idatzi parte-hartzaile guztien izena.', 'Els noms han de ser diferents dins de la mateixa taula.': 'Izenek desberdinak izan behar dute mahai berean.', 'La partida en curs se substituirà. Vols continuar?': 'Abian dagoen partida ordezkatuko da. Jarraitu nahi duzu?', 'Taula sense número': 'Zenbakirik gabeko mahaia', 'Selecciona com es reparteix el compte.': 'Hautatu kontua nola banatu.', 'A patxes necessita almenys una persona seleccionada.': 'Denon artean ordaintzeko pertsona bat hautatu behar da gutxienez.', 'El repartiment manual suma {allocated} i ha de sumar {total}.': 'Eskuzko banaketak {allocated} batzen du eta {total} izan behar du.', '{players} arribarà o superarà el topall i la partida haurà acabat.': '{players} mugara iritsiko da edo gaindituko du, eta partida amaituko da.', '{player} ja té el màxim de 10 cartes a la mà.': '{player}(e)k dagoeneko 10 kartako gehienekoa du eskuan.', 'Revisa el repartiment abans de registrar la ronda.': 'Berrikusi banaketa txanda erregistratu aurretik.', 'Ronda registrada.': 'Txanda erregistratuta.', 'S’ha desfet l’última ronda.': 'Azken txanda desegin da.', 'Registra almenys una ronda abans de finalitzar.': 'Erregistratu gutxienez txanda bat amaitu aurretik.', 'Algú ha arribat o superat el topall. La partida ha acabat.': 'Norbait mugara iritsi da edo gainditu du. Partida amaitu da.', 'Ha pagat': 'Ordaindu du', 'porta': 'gainean darama', 'Resultat': 'Emaitza', 'Resultat final de la partida': 'Partidaren azken emaitza', 'Enllaç copiat.': 'Esteka kopiatuta.', 'No s’ha pogut compartir. Mantén premut el QR per mostrar-lo.': 'Ezin izan da partekatu. Eduki QR-a sakatuta erakusteko.', 'Desempat aplicat.': 'Desberdinketa aplikatuta.',
      'Aquest QR no és un resultat compatible.': 'QR hau ez da emaitza bateragarria.', 'El resultat ha de contenir entre 3 i 8 participants.': 'Emaitzak 3 eta 8 parte-hartzaile artean izan behar ditu.', 'El resultat conté dades incompletes.': 'Emaitzak datu osatugabeak ditu.', 'No s’ha pogut carregar el generador QR.': 'Ezin izan da QR sorgailua kargatu.', 'A iOS: Compartir → Afegeix a la pantalla d’inici.': 'iOS-en: Partekatu → Gehitu hasierako pantailara.', 'Obre el menú del navegador i tria “Instal·la l’aplicació”.': 'Ireki nabigatzailearen menua eta aukeratu «Instalatu aplikazioa».',
      'La classificació apareixerà després d’incorporar el primer QR.': 'Sailkapena lehen QR-a gehitu ondoren agertuko da.', 'Pos.': 'Pos.', 'Victòries': 'Garaipenak', 'Conservat': 'Mantendua', 'Estalvis totals': 'Aurrezki guztira', 'Compten': 'Zenbatzen dira', 'Descarts': 'Baztertuak', 'Diners computables': 'Zenbatutako dirua', 'Ronda de torneig': 'Txapelketa-txanda', 'rondes internes': 'barne-txanda', 'descartat': 'baztertua', 'Compten els {counted} millors resultats de cada participant.': 'Parte-hartzaile bakoitzaren {counted} emaitza onenak zenbatzen dira.', '{players} ja té resultat a la ronda {round}.': '{players}(e)k badu emaitza {round}. txandan.', 'Participant eliminat': 'Ezabatutako parte-hartzailea', 'Aquest navegador no permet accedir a la càmera. Prova “Llegeix una imatge”.': 'Nabigatzaile honek ez du kamerarako sarbiderik ematen. Saiatu «Irakurri irudi bat».', 'Dona permís a la càmera i enquadra el QR.': 'Eman kamerari baimena eta kokatu QR-a markoan.', 'Buscant el codi…': 'Kodea bilatzen…', 'No s’ha pogut obrir la càmera. Revisa el permís o llegeix una imatge.': 'Ezin izan da kamera ireki. Berrikusi baimena edo irakurri irudi bat.', 'No s’ha trobat cap QR llegible a la imatge.': 'Ez da QR irakurgarririk aurkitu irudian.', 'No s’ha pogut llegir la imatge.': 'Ezin izan da irudia irakurri.', 'Aquesta partida ja havia estat incorporada.': 'Partida hau lehendik gehituta zegoen.', 'QR no reconegut.': 'QR ezezaguna.',
      'Identitat al torneig': 'Txapelketako identitatea', 'Persona nova': 'Pertsona berria', 'Coincidència': 'Bat-etortzea', 'Potser': 'Agian', 'Dos noms de la mateixa taula no poden correspondre a una sola persona.': 'Mahai bereko bi izen ezin dira pertsona bera izan.', 'Resultat incorporat al torneig.': 'Emaitza txapelketara gehituta.', 'Vols eliminar aquest resultat del torneig?': 'Emaitza hau txapelketatik ezabatu nahi duzu?', 'Resultat eliminat.': 'Emaitza ezabatuta.', 'Aquest nom ja correspon a un altre participant. Pots fusionar-los.': 'Izen hau beste parte-hartzaile bati dagokio. Batu ditzakezu.', 'Nom actualitzat.': 'Izena eguneratuta.', 'Selecciona dues persones diferents.': 'Hautatu bi pertsona desberdin.', 'Vols fusionar “{remove}” dins de “{keep}”?': '«{remove}» «{keep}» barruan batu nahi duzu?', 'Participants fusionats.': 'Parte-hartzaileak batuta.', 'La còpia substituirà el torneig actual. Vols continuar?': 'Kopiak uneko txapelketa ordezkatuko du. Jarraitu nahi duzu?', 'Còpia restaurada.': 'Kopia leheneratuta.', 'El fitxer no és una còpia vàlida del torneig.': 'Fitxategia ez da txapelketaren baliozko kopia.', 'Vols esborrar totes les partides i participants d’aquest torneig?': 'Txapelketa honetako partida eta parte-hartzaile guztiak ezabatu nahi dituzu?', 'Torneig esborrat.': 'Txapelketa ezabatuta.'
    },
    gl: {
      'Idioma': 'Idioma', 'Participant': 'Participante', 'Mà': 'Man', 'de': 'de', 'Compte': 'Conta', 'propina': 'propina', 'rondes': 'roldas', 'partides': 'partidas', 'també': 'tamén', 'finalitzada': 'finalizada', 'posició': 'posición', 'Configuració del torneig': 'Configuración do torneo', 'Nom del torneig': 'Nome do torneo', 'Torneig de La Cuenta': 'Torneo de La Cuenta', 'Rondes de torneig': 'Roldas de torneo', 'Pitjors resultats descartats': 'Peores resultados descartados', 'Compten els 3 millors resultats de cada participant.': 'Contan os 3 mellores resultados de cada participante.', 'Ronda del torneig': 'Rolda do torneo',
      'Desempat oficial': 'Desempate oficial', 'Si hi ha empat en estalvis, guanya qui porti més diners a sobre. Introdueix-los només per a les persones empatades.': 'Se hai empate nos aforros, gaña quen leve máis cartos encima. Introdúceos só para as persoas empatadas.', 'Aplica el desempat': 'Aplicar o desempate', 'Guanya qui acumula més diners finals. Els empats mantenen la mateixa posició.': 'Gaña quen acumula máis cartos finais. Os empates manteñen a mesma posición.',
      'Escriu el nom de tots els participants.': 'Escribe o nome de todas as persoas participantes.', 'Els noms han de ser diferents dins de la mateixa taula.': 'Os nomes deben ser distintos dentro da mesma mesa.', 'La partida en curs se substituirà. Vols continuar?': 'Substituirase a partida en curso. Queres continuar?', 'Taula sense número': 'Mesa sen número', 'Selecciona com es reparteix el compte.': 'Selecciona como se reparte a conta.', 'A patxes necessita almenys una persona seleccionada.': 'A partes precisa polo menos unha persoa seleccionada.', 'El repartiment manual suma {allocated} i ha de sumar {total}.': 'O reparto manual suma {allocated} e debe sumar {total}.', '{players} arribarà o superarà el topall i la partida haurà acabat.': '{players} chegará ou superará o límite e a partida rematará.', '{player} ja té el màxim de 10 cartes a la mà.': '{player} xa ten o máximo de 10 cartas na man.', 'Revisa el repartiment abans de registrar la ronda.': 'Revisa o reparto antes de rexistrar a rolda.', 'Ronda registrada.': 'Rolda rexistrada.', 'S’ha desfet l’última ronda.': 'Desfíxose a última rolda.', 'Registra almenys una ronda abans de finalitzar.': 'Rexistra polo menos unha rolda antes de finalizar.', 'Algú ha arribat o superat el topall. La partida ha acabat.': 'Alguén chegou ou superou o límite. A partida rematou.', 'Ha pagat': 'Pagou', 'porta': 'leva', 'Resultat': 'Resultado', 'Resultat final de la partida': 'Resultado final da partida', 'Enllaç copiat.': 'Ligazón copiada.', 'No s’ha pogut compartir. Mantén premut el QR per mostrar-lo.': 'Non se puido compartir. Mantén premido o QR para mostralo.', 'Desempat aplicat.': 'Desempate aplicado.',
      'Aquest QR no és un resultat compatible.': 'Este QR non é un resultado compatible.', 'El resultat ha de contenir entre 3 i 8 participants.': 'O resultado debe conter entre 3 e 8 participantes.', 'El resultat conté dades incompletes.': 'O resultado contén datos incompletos.', 'No s’ha pogut carregar el generador QR.': 'Non se puido cargar o xerador QR.', 'A iOS: Compartir → Afegeix a la pantalla d’inici.': 'En iOS: Compartir → Engadir á pantalla de inicio.', 'Obre el menú del navegador i tria “Instal·la l’aplicació”.': 'Abre o menú do navegador e escolle «Instalar a aplicación».',
      'La classificació apareixerà després d’incorporar el primer QR.': 'A clasificación aparecerá despois de incorporar o primeiro QR.', 'Pos.': 'Pos.', 'Victòries': 'Vitorias', 'Conservat': 'Conservado', 'Estalvis totals': 'Aforros totais', 'Compten': 'Contan', 'Descarts': 'Descartes', 'Diners computables': 'Cartos computables', 'Ronda de torneig': 'Rolda de torneo', 'rondes internes': 'roldas internas', 'descartat': 'descartado', 'Compten els {counted} millors resultats de cada participant.': 'Contan os {counted} mellores resultados de cada participante.', '{players} ja té resultat a la ronda {round}.': '{players} xa ten resultado na rolda {round}.', 'Participant eliminat': 'Participante eliminado', 'Aquest navegador no permet accedir a la càmera. Prova “Llegeix una imatge”.': 'Este navegador non permite acceder á cámara. Proba «Ler unha imaxe».', 'Dona permís a la càmera i enquadra el QR.': 'Dálle permiso á cámara e enmarca o QR.', 'Buscant el codi…': 'Buscando o código…', 'No s’ha pogut obrir la càmera. Revisa el permís o llegeix una imatge.': 'Non se puido abrir a cámara. Revisa o permiso ou le unha imaxe.', 'No s’ha trobat cap QR llegible a la imatge.': 'Non se atopou ningún QR lexible na imaxe.', 'No s’ha pogut llegir la imatge.': 'Non se puido ler a imaxe.', 'Aquesta partida ja havia estat incorporada.': 'Esta partida xa fora incorporada.', 'QR no reconegut.': 'QR non recoñecido.',
      'Identitat al torneig': 'Identidade no torneo', 'Persona nova': 'Persoa nova', 'Coincidència': 'Coincidencia', 'Potser': 'Quizais', 'Dos noms de la mateixa taula no poden correspondre a una sola persona.': 'Dous nomes da mesma mesa non poden corresponder a unha soa persoa.', 'Resultat incorporat al torneig.': 'Resultado incorporado ao torneo.', 'Vols eliminar aquest resultat del torneig?': 'Queres eliminar este resultado do torneo?', 'Resultat eliminat.': 'Resultado eliminado.', 'Aquest nom ja correspon a un altre participant. Pots fusionar-los.': 'Este nome xa corresponde a outro participante. Podes fusionalos.', 'Nom actualitzat.': 'Nome actualizado.', 'Selecciona dues persones diferents.': 'Selecciona dúas persoas diferentes.', 'Vols fusionar “{remove}” dins de “{keep}”?': 'Queres fusionar «{remove}» dentro de «{keep}»?', 'Participants fusionats.': 'Participantes fusionados.', 'La còpia substituirà el torneig actual. Vols continuar?': 'A copia substituirá o torneo actual. Queres continuar?', 'Còpia restaurada.': 'Copia restaurada.', 'El fitxer no és una còpia vàlida del torneig.': 'O ficheiro non é unha copia válida do torneo.', 'Vols esborrar totes les partides i participants d’aquest torneig?': 'Queres borrar todas as partidas e participantes deste torneo?', 'Torneig esborrat.': 'Torneo borrado.'
    }
  };
  const tournamentExtras = {
    es: {
      'Taules per ronda': 'Mesas por ronda', 'Crea torneig': 'Crear torneo', '3 rondes · 2 taules per ronda · compten els 3 millors resultats.': '3 rondas · 2 mesas por ronda · cuentan los 3 mejores resultados.', 'Crea la ronda següent': 'Crear la ronda siguiente', 'Rondes creades': 'Rondas creadas', 'Taula del torneig': 'Mesa del torneo', 'Actualitza el torneig': 'Actualizar el torneo',
      '{rounds} rondes · {tables} taules per ronda · compten els {counted} millors resultats.': '{rounds} rondas · {tables} mesas por ronda · cuentan los {counted} mejores resultados.', 'Mostra la ronda': 'Mostrar la ronda', 'Resultat rebut': 'Resultado recibido', 'Pendent de QR': 'Pendiente de QR', 'Assigna aquesta taula en escanejar.': 'Asigna esta mesa al escanear.', 'taules amb resultat': 'mesas con resultado', 'emmagatzematge persistent actiu': 'almacenamiento persistente activo', 'Crea primer el torneig i les seves taules.': 'Crea primero el torneo y sus mesas.', 'Cap taula pendent': 'Ninguna mesa pendiente', 'Aquesta ronda no té cap taula pendent.': 'Esta ronda no tiene ninguna mesa pendiente.', 'No es poden fusionar: tots dos tenen resultat a la ronda {round}.': 'No se pueden fusionar: ambos tienen resultado en la ronda {round}.', 'Configuració actualitzada.': 'Configuración actualizada.', 'Torneig creat. Escaneja els resultats de la primera ronda.': 'Torneo creado. Escanea los resultados de la primera ronda.', 'Completa totes les taules abans de crear la ronda següent.': 'Completa todas las mesas antes de crear la ronda siguiente.', 'Ronda nova creada.': 'Nueva ronda creada.',
      'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències úniques es preseleccionen; si un nom pot ser més d’una persona, cal triar-la.': 'Para cada nombre, confirma si es una persona existente o nueva. Las coincidencias únicas se preseleccionan; si un nombre puede ser más de una persona, hay que elegirla.', 'Tria entre persones amb el mateix nom': 'Elige entre personas con el mismo nombre', 'Ja té resultat en aquesta ronda': 'Ya tiene resultado en esta ronda', 'Confirma la identitat de tots els noms abans d’incorporar el resultat.': 'Confirma la identidad de todos los nombres antes de incorporar el resultado.', 'L’enllaç no conté cap resultat importable.': 'El enlace no contiene ningún resultado importable.', 'No s’ha pogut dibuixar el QR. Pots compartir l’enllaç del resultat.': 'No se ha podido dibujar el QR. Puedes compartir el enlace del resultado.', 'No s’ha pogut preparar el resultat. Torna-ho a provar.': 'No se ha podido preparar el resultado. Vuelve a intentarlo.'
    },
    eu: {
      'Taules per ronda': 'Mahaiak txandako', 'Crea torneig': 'Sortu txapelketa', '3 rondes · 2 taules per ronda · compten els 3 millors resultats.': '3 txanda · 2 mahai txandako · 3 emaitza onenak zenbatzen dira.', 'Crea la ronda següent': 'Sortu hurrengo txanda', 'Rondes creades': 'Sortutako txandak', 'Taula del torneig': 'Txapelketako mahaia', 'Actualitza el torneig': 'Eguneratu txapelketa',
      '{rounds} rondes · {tables} taules per ronda · compten els {counted} millors resultats.': '{rounds} txanda · {tables} mahai txandako · {counted} emaitza onenak zenbatzen dira.', 'Mostra la ronda': 'Erakutsi txanda', 'Resultat rebut': 'Emaitza jasota', 'Pendent de QR': 'QR-aren zain', 'Assigna aquesta taula en escanejar.': 'Esleitu mahai hau eskaneatzean.', 'taules amb resultat': 'emaitza duten mahai', 'emmagatzematge persistent actiu': 'biltegiratze iraunkorra aktibo', 'Crea primer el torneig i les seves taules.': 'Sortu lehenik txapelketa eta mahaiak.', 'Cap taula pendent': 'Ez dago mahairik zain', 'Aquesta ronda no té cap taula pendent.': 'Txanda honetan ez dago mahairik zain.', 'No es poden fusionar: tots dos tenen resultat a la ronda {round}.': 'Ezin dira batu: biek dute emaitza {round}. txandan.', 'Configuració actualitzada.': 'Konfigurazioa eguneratuta.', 'Torneig creat. Escaneja els resultats de la primera ronda.': 'Txapelketa sortuta. Eskaneatu lehen txandako emaitzak.', 'Completa totes les taules abans de crear la ronda següent.': 'Osatu mahai guztiak hurrengo txanda sortu aurretik.', 'Ronda nova creada.': 'Txanda berria sortuta.',
      'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències úniques es preseleccionen; si un nom pot ser més d’una persona, cal triar-la.': 'Izen bakoitzean, baieztatu lehendik dagoen pertsona den ala berria. Bat-etortze bakarrak aurrez hautatzen dira; izenak pertsona bati baino gehiagori badagokio, aukeratu egin behar da.', 'Tria entre persones amb el mateix nom': 'Aukeratu izen bereko pertsonen artean', 'Ja té resultat en aquesta ronda': 'Dagoeneko badu emaitza txanda honetan', 'Confirma la identitat de tots els noms abans d’incorporar el resultat.': 'Baieztatu izen guztien identitatea emaitza gehitu aurretik.', 'L’enllaç no conté cap resultat importable.': 'Estekak ez du inporta daitekeen emaitzarik.', 'No s’ha pogut dibuixar el QR. Pots compartir l’enllaç del resultat.': 'Ezin izan da QR-a marraztu. Emaitzaren esteka parteka dezakezu.', 'No s’ha pogut preparar el resultat. Torna-ho a provar.': 'Ezin izan da emaitza prestatu. Saiatu berriro.'
    },
    gl: {
      'Taules per ronda': 'Mesas por rolda', 'Crea torneig': 'Crear torneo', '3 rondes · 2 taules per ronda · compten els 3 millors resultats.': '3 roldas · 2 mesas por rolda · contan os 3 mellores resultados.', 'Crea la ronda següent': 'Crear a seguinte rolda', 'Rondes creades': 'Roldas creadas', 'Taula del torneig': 'Mesa do torneo', 'Actualitza el torneig': 'Actualizar o torneo',
      '{rounds} rondes · {tables} taules per ronda · compten els {counted} millors resultats.': '{rounds} roldas · {tables} mesas por rolda · contan os {counted} mellores resultados.', 'Mostra la ronda': 'Mostrar a rolda', 'Resultat rebut': 'Resultado recibido', 'Pendent de QR': 'Pendente de QR', 'Assigna aquesta taula en escanejar.': 'Asigna esta mesa ao escanear.', 'taules amb resultat': 'mesas con resultado', 'emmagatzematge persistent actiu': 'almacenamento persistente activo', 'Crea primer el torneig i les seves taules.': 'Crea primeiro o torneo e as súas mesas.', 'Cap taula pendent': 'Ningunha mesa pendente', 'Aquesta ronda no té cap taula pendent.': 'Esta rolda non ten ningunha mesa pendente.', 'No es poden fusionar: tots dos tenen resultat a la ronda {round}.': 'Non se poden fusionar: ambos teñen resultado na rolda {round}.', 'Configuració actualitzada.': 'Configuración actualizada.', 'Torneig creat. Escaneja els resultats de la primera ronda.': 'Torneo creado. Escanea os resultados da primeira rolda.', 'Completa totes les taules abans de crear la ronda següent.': 'Completa todas as mesas antes de crear a seguinte rolda.', 'Ronda nova creada.': 'Nova rolda creada.',
      'Per cada nom, confirma si és una persona existent o una incorporació nova. Les coincidències úniques es preseleccionen; si un nom pot ser més d’una persona, cal triar-la.': 'Para cada nome, confirma se é unha persoa existente ou nova. As coincidencias únicas preselecciónanse; se un nome pode ser máis dunha persoa, hai que escollela.', 'Tria entre persones amb el mateix nom': 'Escolle entre persoas co mesmo nome', 'Ja té resultat en aquesta ronda': 'Xa ten resultado nesta rolda', 'Confirma la identitat de tots els noms abans d’incorporar el resultat.': 'Confirma a identidade de todos os nomes antes de incorporar o resultado.', 'L’enllaç no conté cap resultat importable.': 'A ligazón non contén ningún resultado importable.', 'No s’ha pogut dibuixar el QR. Pots compartir l’enllaç del resultat.': 'Non se puido debuxar o QR. Podes compartir a ligazón do resultado.', 'No s’ha pogut preparar el resultat. Torna-ho a provar.': 'Non se puido preparar o resultado. Téntao de novo.'
    }
  };
  Object.entries(extras).forEach(([code, values]) => Object.assign(catalogs[code], values, tournamentExtras[code]));
  const supported = ['ca', 'es', 'eu', 'gl'];
  const textSources = new WeakMap();
  const attrSources = new WeakMap();
  let language = localStorage.getItem('lcc.language') || (supported.includes(navigator.language?.slice(0, 2)) ? navigator.language.slice(0, 2) : 'ca');

  function t(source, variables = {}) {
    let value = catalogs[language]?.[source] || source;
    Object.entries(variables).forEach(([key, replacement]) => { value = value.replaceAll(`{${key}}`, replacement); });
    return value;
  }

  function apply(root = document) {
    document.documentElement.lang = language;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (['SCRIPT', 'STYLE'].includes(node.parentElement?.tagName)) continue;
      const trimmed = node.textContent.trim(); if (!trimmed) continue;
      if (!textSources.has(node)) textSources.set(node, trimmed);
      const source = textSources.get(node); const translated = t(source);
      node.textContent = node.textContent.replace(trimmed, translated);
    }
    root.querySelectorAll?.('*').forEach(element => {
      let sources = attrSources.get(element); if (!sources) { sources = {}; attrSources.set(element, sources); }
      ['placeholder', 'aria-label', 'title'].forEach(attribute => {
        if (!element.hasAttribute(attribute)) return;
        if (!(attribute in sources)) sources[attribute] = element.getAttribute(attribute);
        element.setAttribute(attribute, t(sources[attribute]));
      });
    });
    if (!document.documentElement.dataset.originalTitle) document.documentElement.dataset.originalTitle = document.title;
    document.title = t(document.documentElement.dataset.originalTitle);
    const selector = document.querySelector('#language-select'); if (selector) selector.value = language;
  }

  function setLanguage(next) {
    if (!supported.includes(next)) return;
    language = next; localStorage.setItem('lcc.language', language); apply(); window.dispatchEvent(new CustomEvent('lcc:languagechange'));
  }

  globalThis.LCCI18N = { t, apply, setLanguage, get language() { return language; }, locale() { return ({ ca: 'ca-ES', es: 'es-ES', eu: 'eu-ES', gl: 'gl-ES' })[language]; } };
})();
